[ctp]
front_md = "tcp://211.136.125.127:51213"
front_td = "tcp://211.136.125.127:51205"
auth_id = ""
auth_code = ""
broker_id = ""
user_id = "your_id"
password = "your_pwd"

[openctp]
front_md = "tcp://121.37.80.177:20004"
front_td = "tcp://121.37.80.177:20002"
auth_id = ""
auth_code = ""
broker_id = ""
user_id = "your_id"
password = "your_pwd"

[default]
# choose from ["ctp", "openctp"]
mode = "openctp"
# choose from ["lin64", "win64"]
platform = "lin64"
