[default]
lib_dir = "openctp"
# choose from ["lin64", "win64"]
platform = "lin64"

[user]
front_td = "tcp://121.37.80.177:20002"
front_md = "tcp://121.37.80.177:20004"
auth_id = ""
auth_code = ""
broker_id = ""
user_id = "your_id"
password = "your_pwd"
